"""initial_schema

Revision ID: 4b42116b2193
Revises: 
Create Date: 2026-07-22 12:50:29.454354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b42116b2193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('investigation_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_investigation_type'), 'cases', ['investigation_type'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('agent_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_results_agent_name'), 'agent_results', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_results_case_id'), 'agent_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_results_created_at'), 'agent_results', ['created_at'], unique=False)
    op.create_table('fusion_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('final_verdict', sa.String(length=50), nullable=True),
    sa.Column('overall_risk', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_reports_case_id'), 'fusion_reports', ['case_id'], unique=True)
    op.create_index(op.f('ix_fusion_reports_created_at'), 'fusion_reports', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fusion_reports_created_at'), table_name='fusion_reports')
    op.drop_index(op.f('ix_fusion_reports_case_id'), table_name='fusion_reports')
    op.drop_table('fusion_reports')
    op.drop_index(op.f('ix_agent_results_created_at'), table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_case_id'), table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_agent_name'), table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_investigation_type'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
