import { useState, useMemo } from 'react';
import { Search, FilterX } from 'lucide-react';
import CaseTable from '../components/CaseTable';
import { mockCases } from '../data/mockCases';
import type { CaseStatus, RiskLevel } from '../types/case';

export default function Cases() {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<CaseStatus | 'All'>('All');
  const [riskFilter, setRiskFilter] = useState<RiskLevel | 'All'>('All');

  const filteredCases = useMemo(() => {
    const results = mockCases.filter((c) => {
      const matchesSearch = 
        c.case_id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.victim_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.title.toLowerCase().includes(searchQuery.toLowerCase());
      
      const matchesStatus = statusFilter === 'All' || c.status === statusFilter;
      const matchesRisk = riskFilter === 'All' || c.risk_level === riskFilter;

      return matchesSearch && matchesStatus && matchesRisk;
    });

    return results.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  }, [searchQuery, statusFilter, riskFilter]);

  const clearFilters = () => {
    setSearchQuery('');
    setStatusFilter('All');
    setRiskFilter('All');
  };

  return (
    <div className="space-y-6">
      <div className="border-b border-gray-200 pb-5 flex flex-col md:flex-row md:items-end md:justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:tracking-tight">
            Case Management
          </h2>
          <p className="mt-2 text-sm text-gray-500">
            Browse and filter investigations generated by the Intelligence Fusion engine.
          </p>
        </div>
        <div className="text-sm font-medium text-gray-700 bg-gray-100 px-3 py-1.5 rounded-md self-start md:self-auto">
          {searchQuery || statusFilter !== 'All' || riskFilter !== 'All' 
            ? `Showing ${filteredCases.length} of ${mockCases.length} Cases`
            : `Showing ${mockCases.length} Cases`
          }
        </div>
      </div>

      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between bg-white p-4 rounded-lg shadow-sm border border-gray-200">
        <div className="relative flex-1 max-w-md">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <Search className="h-5 w-5 text-gray-400" aria-hidden="true" />
          </div>
          <input
            type="text"
            className="block w-full rounded-md border-0 py-2 pl-10 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6 transition-shadow"
            placeholder="Search by Case ID, Victim, or Investigation..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
        
        <div className="flex items-center gap-3">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as CaseStatus | 'All')}
            className="block rounded-md border-0 py-2 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-blue-600 sm:text-sm sm:leading-6 transition-shadow"
            aria-label="Filter by Status"
          >
            <option value="All">All Statuses</option>
            <option value="Open">Open</option>
            <option value="Under Review">Under Review</option>
            <option value="Closed">Closed</option>
          </select>

          <select
            value={riskFilter}
            onChange={(e) => setRiskFilter(e.target.value as RiskLevel | 'All')}
            className="block rounded-md border-0 py-2 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-blue-600 sm:text-sm sm:leading-6 transition-shadow"
            aria-label="Filter by Risk Level"
          >
            <option value="All">All Risks</option>
            <option value="Critical">Critical</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>

          {(searchQuery || statusFilter !== 'All' || riskFilter !== 'All') && (
            <button
              onClick={clearFilters}
              className="inline-flex items-center p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-md transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-600"
              title="Clear filters"
              aria-label="Clear filters"
            >
              <FilterX className="h-5 w-5" />
            </button>
          )}
        </div>
      </div>

      <CaseTable cases={filteredCases} />
    </div>
  );
}
