import { useState, useMemo, useEffect, useCallback } from 'react';
import { Search, FilterX, FolderOpen, RefreshCw } from 'lucide-react';
import CaseTable from '../components/CaseTable';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorState from '../components/ErrorState';
import { caseService, classifyApiError } from '../services/api';
import type { CaseStatus, RiskLevel, InvestigationCase } from '../types/case';

export default function Cases() {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<CaseStatus | 'All'>('All');
  const [riskFilter, setRiskFilter] = useState<RiskLevel | 'All'>('All');

  // Strictly backend-only; no mock data injected
  const [casesList, setCasesList] = useState<InvestigationCase[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [errorVariant, setErrorVariant] = useState<string | null>(null);

  const fetchCases = useCallback(() => {
    let isMounted = true;
    setIsLoading(true);
    setErrorVariant(null);

    caseService
      .getCases()
      .then((dbCases: any[]) => {
        if (!isMounted) return;
        if (!Array.isArray(dbCases)) {
          setCasesList([]);
          return;
        }
        const mapped: InvestigationCase[] = dbCases.map((c) => ({
          case_id: c.case_id,
          title:
            c.metadata?.title ||
            `${(c.investigation_type || 'Investigation').toUpperCase()} (${c.case_id.slice(0, 8)})`,
          victim_name: c.metadata?.victim_name || 'Not Available',
          assigned_officer: c.metadata?.assigned_officer || 'Unassigned',
          status: c.status === 'completed' ? 'Closed' : c.status === 'processing' ? 'Under Review' : 'Open',
          risk_level:
            (c.fusion_report?.overall_risk || 0) >= 75
              ? 'Critical'
              : (c.fusion_report?.overall_risk || 0) >= 50
              ? 'High'
              : (c.fusion_report?.overall_risk || 0) >= 25
              ? 'Medium'
              : 'Low',
          created_at: c.created_at || new Date().toISOString(),
          updated_at: c.updated_at || c.created_at || new Date().toISOString(),
        }));
        setCasesList(mapped);
      })
      .catch((err: Error) => {
        if (!isMounted) return;
        const variant = classifyApiError(err) || 'default';
        setErrorVariant(variant);
        setCasesList([]);
      })
      .finally(() => {
        if (isMounted) setIsLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    const cleanup = fetchCases();
    return cleanup;
  }, [fetchCases]);

  const filteredCases = useMemo(() => {
    const results = casesList.filter((c) => {
      const matchesSearch =
        c.case_id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.victim_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.title.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesStatus = statusFilter === 'All' || c.status === statusFilter;
      const matchesRisk = riskFilter === 'All' || c.risk_level === riskFilter;

      return matchesSearch && matchesStatus && matchesRisk;
    });

    return results.sort(
      (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    );
  }, [casesList, searchQuery, statusFilter, riskFilter]);

  const clearFilters = () => {
    setSearchQuery('');
    setStatusFilter('All');
    setRiskFilter('All');
  };

  const hasFilters = !!(searchQuery || statusFilter !== 'All' || riskFilter !== 'All');

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="border-b border-white/10 pb-5 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3">
        <div className="min-w-0">
          <h2 className="text-xl sm:text-2xl font-extrabold leading-7 text-white tracking-tight break-words">
            Case Management
          </h2>
          <p className="mt-1 text-sm text-gray-400">
            Browse and filter investigations generated by the Intelligence Fusion engine.
          </p>
        </div>
        {!isLoading && !errorVariant && (
          <div className="text-xs font-bold text-gray-300 bg-[#111827] border border-white/10 px-3.5 py-2 rounded-xl self-start sm:self-auto shrink-0 shadow-sm">
            {hasFilters
              ? `Showing ${filteredCases.length} of ${casesList.length}`
              : `${casesList.length} ${casesList.length === 1 ? 'Case' : 'Cases'}`}
          </div>
        )}
      </div>

      {/* Backend error */}
      {errorVariant && !isLoading && (
        <ErrorState variant={errorVariant as any} onRetry={fetchCases} />
      )}

      {/* Filters row */}
      {!errorVariant && (
        <div className="glass-card flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between p-4 border border-white/10 rounded-2xl bg-[#111827]/70 backdrop-blur-md shadow-xl">
          <div className="relative flex-1 min-w-0">
            <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3.5">
              <Search className="h-4 w-4 text-gray-400" aria-hidden="true" />
            </div>
            <input
              type="text"
              className="block w-full rounded-xl bg-[#0F172A] border border-white/10 py-2.5 pl-10 pr-3 text-white placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 text-sm leading-6 transition-all min-h-[44px]"
              placeholder="Search by Case ID, Victim, or Investigation…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              aria-label="Search cases"
            />
          </div>

          <div className="flex flex-wrap items-center gap-2.5">
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as CaseStatus | 'All')}
              className="rounded-xl bg-[#0F172A] border border-white/10 py-2.5 pl-3.5 pr-8 text-white focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 text-sm leading-6 transition-all min-h-[44px] cursor-pointer"
              aria-label="Filter by Status"
            >
              <option value="All" className="bg-[#0F172A] text-white">All Statuses</option>
              <option value="Open" className="bg-[#0F172A] text-white">Open</option>
              <option value="Under Review" className="bg-[#0F172A] text-white">Under Review</option>
              <option value="Closed" className="bg-[#0F172A] text-white">Closed</option>
            </select>

            <select
              value={riskFilter}
              onChange={(e) => setRiskFilter(e.target.value as RiskLevel | 'All')}
              className="rounded-xl bg-[#0F172A] border border-white/10 py-2.5 pl-3.5 pr-8 text-white focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 text-sm leading-6 transition-all min-h-[44px] cursor-pointer"
              aria-label="Filter by Risk Level"
            >
              <option value="All" className="bg-[#0F172A] text-white">All Risks</option>
              <option value="Critical" className="bg-[#0F172A] text-white">Critical</option>
              <option value="High" className="bg-[#0F172A] text-white">High</option>
              <option value="Medium" className="bg-[#0F172A] text-white">Medium</option>
              <option value="Low" className="bg-[#0F172A] text-white">Low</option>
            </select>

            {hasFilters && (
              <button
                onClick={clearFilters}
                className="inline-flex items-center justify-center p-2.5 text-gray-400 hover:text-white hover:bg-white/10 rounded-xl transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 min-h-[44px] min-w-[44px]"
                title="Clear filters"
                aria-label="Clear all filters"
              >
                <FilterX className="h-4 w-4" aria-hidden="true" />
              </button>
            )}
          </div>
        </div>
      )}

      {/* Loading state */}
      {isLoading && (
        <div className="glass-card border border-white/10 rounded-2xl bg-[#111827]/70 p-12">
          <LoadingSpinner message="Loading cases…" />
        </div>
      )}

      {/* Empty workspace state */}
      {!isLoading && !errorVariant && casesList.length === 0 && (
        <div className="glass-card flex flex-col items-center justify-center border border-white/10 bg-[#111827]/70 backdrop-blur-md rounded-2xl p-12 sm:p-16 text-center shadow-xl">
          <div className="mb-4 p-4 bg-slate-900/80 border border-slate-800 rounded-full">
            <FolderOpen className="h-8 w-8 text-blue-400" aria-hidden="true" />
          </div>
          <h3 className="text-lg font-bold text-white mb-1">No investigations available</h3>
          <p className="text-sm text-gray-400 max-w-sm mb-6 leading-relaxed">
            This workspace does not currently contain any investigations. Submit a case through the
            Citizen Portal to get started.
          </p>
          <button
            onClick={fetchCases}
            className="inline-flex items-center gap-2 rounded-xl bg-blue-600 hover:bg-blue-500 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-blue-900/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 transition-all min-h-[44px]"
          >
            <RefreshCw className="h-4 w-4" aria-hidden="true" />
            <span>Refresh</span>
          </button>
        </div>
      )}

      {/* Cases table */}
      {!isLoading && !errorVariant && casesList.length > 0 && (
        <CaseTable cases={filteredCases} />
      )}
    </div>
  );
}
